### ISSUE TITLE
Add ChunkBlockOffsets to contentIndex.

### ISSUE THREAD

**Issue by tvandijck** [DanEngelbrecht/longtail#119]
Right now we cache the ChunkHash -> BlockIndex when constructing the BlockStoreStorage.
But to be able to pre-calculate chunk range information if would be useful to have the BlockOffset as well.

It would entirely eliminate the need for the "block_chunk_lookup" table in BlockStoreStorageAPI_ReadFromBlock..

In C# I'd get:

            var chunkHashToBlockIndexLookup = new Dictionary<Hash, int>();
            for (var c = 0; c < contentIndex.ChunkCount; ++c)
            {
                var blockIndex = (int)contentIndex.ChunkBlockIndices[c];
                chunkHashToBlockIndexLookup.Add(contentIndex.ChunkHashes[c], blockIndex);
            }

            m_chunkRanges = new ChunkRange[versionIndex.ChunkCount];

            for (var i = 0; i < assetCount; ++i)
            {
                var chunkCount = versionIndex.AssetChunkCounts[i];
                var chunkStartIndex = (int)versionIndex.AssetChunkIndexStarts[i];
                uint chunkOffset = 0;
                for (uint c = 0; c < chunkCount; ++c)
                {
                    var chunkIndex = versionIndex.AssetChunkIndices[(int)(chunkStartIndex + c)];
                    var chunkHash = versionIndex.ChunkHashes[(int)chunkIndex];

                    if (chunkHashToBlockIndexLookup.TryGetValue(chunkHash, out var blockIndex))
                    {
                        var blockHash = m_contentIndex.BlockHashes[blockIndex];
                        m_chunkRanges[chunkStartIndex+c] = new ChunkRange
                        {
                            BlockHash = blockHash,
                            AssetStartOffset = chunkOffset,
                            Size = (int)versionIndex.ChunkSizes[(int)chunkIndex],
                            BlockOffset = m_contentIndex.BlockOffsets[blockIndex]
                        };
                    }

                    chunkOffset += versionIndex.ChunkSizes[(int)chunkIndex];
                }
            }

Which then reduces the Read method to a simple loop:

            public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
            {
                var totalRead = 0;
                while (count > 0 && m_rangeIndex < m_rangeCount)
                {
                    var range = m_blockStore.m_chunkRanges[m_rangeIndex];
                    if (range.StoredBlock == null)
                    {
                        range.StoredBlock = await m_blockStore.m_blockStore.GetAsync(range.BlockHash);
                    }

                    var chunkOffset = (int)(m_position - range.AssetStartOffset);
                    var numRead = Math.Min(count, range.Size - chunkOffset);

                    Array.Copy(range.StoredBlock.BlockData, range.BlockOffset + chunkOffset, buffer, offset, numRead);

                    m_position += numRead;
                    totalRead += numRead;

                    count -= numRead;
                    offset += numRead;

                    if (m_position >= range.AssetStartOffset + range.Size)
                    {
                        m_rangeIndex++;
                    }
                }

                return totalRead;
            }

- zero hash-table lookups.
- Seek would be simple too... just set m_position, and find the m_rangeIndex that overlaps that position, which is just a binary search.
- chunkHashToBlockIndexLookup would no longer need to be stored past the construction of the BlockStoreStorage.

**Comment by DanEngelbrecht** [comment]
Yes, it would make that code a bit easier but the map build/lookup is pretty cheap and adding the offsets would bloat the store index quite a bit. Decided against it for now.
