### ISSUE TITLE
Is Longtail currently limited to handling ~128k files due to how Bikeshed gets initialized?

### ISSUE THREAD

**Issue by Kalmalyzer** [DanEngelbrecht/longtail#160]
I am using `golongtail` to up/downsync pre-built UE4 installations. I'm using it on Linux, and Longtail seems to freeze early when performing an upsync:

```
2021/05/07 20:32:45 {"file": "/home/runner/work/longtail/longtail/src/longtail.c", "func": "Longtail_CreateVersionIndex", "line": "2442", "level": "INFO", "storage_api": "0x2d4b7f0", "hash_api": "0x2d4f370", "chunker_api": "0x7f552c0725f0", "job_api": "0x2d4b8b0", "progress_api": "0x7f552c005570", "optional_cancel_api": "(nil)", "optional_cancel_token": "(nil)", "root_path": "./Scripts/Linux/BuildSteps/../../../UE/LocalBuilds/Engine/Linux", "file_infos": "0x7f54f4044010", "optional_asset_tags": "12320768", "target_chunk_size": "32768", "out_version_index": "0xc000010998", "msg": "[ctx]"}
2021/05/07 20:32:45 {"file": "/home/runner/work/longtail/longtail/lib/bikeshed/longtail_bikeshed.c", "func": "Bikeshed_ReserveJobs", "line": "263", "level": "DEBUG", "job_api": "0x2d4b8b0", "job_count": "154638", "out_job_group": "0x7f553c059ab0", "msg": "[ctx]"}
2021/05/07 20:32:45 {"file": "/home/runner/work/longtail/longtail/lib/bikeshed/longtail_bikeshed.c", "func": "CreateJobGroup", "line": "185", "level": "DEBUG", "job_api": "0x2d4b8b0", "job_count": "154638", "msg": "[ctx]"}
```

When I attempt an upsync of the entire UE folder structure longtail hangs at that message. If I exclude a bunch (so job count goes down to ~100k) then it succeeds.

`job_count` in the last message up there is higher than 128k.
longtail_bikeshed.c has [a couple of hardcoded constants](https://github.com/DanEngelbrecht/longtail/blob/master/lib/bikeshed/longtail_bikeshed.c#L545) (one of which is 131072 for num of tasks) when it initializes Bikeshed.
bikeshed doesn't seem to store the max num tasks internally, and therefore it cannot error in case someone tries to put too many tasks into the library.

I'm not 100% certain, but this looks like a likely culprit. Will investigate further when I get some time (rebuild with raised numbers etc). What is your take?

**Comment by Kalmalyzer** [comment]
... Hmm, yes, this looks likely; we have previously used golongtail 0.0.36 successfully on Windows, which uses longtail 0.0.44. That older version has [considerably higher constants](https://github.com/DanEngelbrecht/longtail/blob/v0.0.44/lib/bikeshed/longtail_bikeshed.c#L432) (1M tasks, 7M dependencies).

**Comment by luke-james-portfolio** [comment]
I've just come up against exactly the same issue as @Kalmalyzer - while trying to upload an installed build of UnrealEngine 4.27 to AWS S3, I get the same output given above.

I have cloned longtail & golongtail and recompiled the static library and golongtail executable with the values given [here](https://github.com/DanEngelbrecht/longtail/blob/v0.0.44/lib/bikeshed/longtail_bikeshed.c#L432).
 
This does fix the 'hanging' problem and I have been able to successfully upsync and downsync my UE4 build from S3 (I'm using W10).

@DanEngelbrecht - generally I would prefer to pull a longtail release from GH as part of my build script so I'm not storing any binaries/executables in GitHub.  Would you be open to looking at formally resolving this limitation?

**Comment by dan-embark** [comment]
It should not really block but I’ll look into to it as soon as I can.

**Comment by dan-embark** [comment]
The reason I reduced the constants was to reduce memory allocation and initialization time, but as I said, it really should not block…

**Comment by luke-james-portfolio** [comment]
I've just come up against exactly the same issue as @Kalmalyzer - while trying to upload an installed build of UnrealEngine 4.27 to AWS S3, I get the same output given above.

I have cloned longtail & golongtail and recompiled the static library and golongtail executable with the values given [here](https://github.com/DanEngelbrecht/longtail/blob/v0.0.44/lib/bikeshed/longtail_bikeshed.c#L432).

This does fix the 'hanging' problem and I have been able to successfully upsync and downsync my UE4 build from S3 (I'm using W10).

@DanEngelbrecht - generally I would prefer to pull a longtail release from GH as part of my build script so I'm not storing any dependent binaries/executables in GitHub. Would you be open to looking at formally resolving this limitation?

**Comment by DanEngelbrecht** [comment]
Yep, will try and fix it as soon as I have some time.

**Comment by DanEngelbrecht** [comment]
@Kalmalyzer Wow, this is really weird, this issue is from May? It does not show up on my regular list of issues. Sorry for taking so long to address it. Trying to look into it now.

**Comment by DanEngelbrecht** [comment]
This fix is no propagated to golongtail as of release https://github.com/DanEngelbrecht/golongtail/releases/tag/v0.2.5
Hopefully this solves your issues @Kalmalyzer and @luke-james-portfolio , again, sorry for letting this go unattended for so long. Actually found a TODO in the code related to this. :P

**Comment by Kalmalyzer** [comment]
Thanks -- much appreciated. Time for us to look at upgrading to the latest version, this was the only blocker we knew of :)
